name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: build docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to docker hub
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: xuqingfeng/brb
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
